[2024-11-26T12:09:46.075+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.send_email manual__2024-11-26T12:09:21.202594+00:00 [queued]>
[2024-11-26T12:09:46.085+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.send_email manual__2024-11-26T12:09:21.202594+00:00 [queued]>
[2024-11-26T12:09:46.086+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-26T12:09:46.101+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): send_email> on 2024-11-26 12:09:21.202594+00:00
[2024-11-26T12:09:46.109+0000] {standard_task_runner.py:57} INFO - Started process 1285 to run task
[2024-11-26T12:09:46.113+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'send_email', 'manual__2024-11-26T12:09:21.202594+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmpulge8odf']
[2024-11-26T12:09:46.116+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask send_email
[2024-11-26T12:09:46.158+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.send_email manual__2024-11-26T12:09:21.202594+00:00 [running]> on host 7f10b2294d44
[2024-11-26T12:09:46.203+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'send_email', field 'files'. Template: ['/opt/***/data/data_drift_dashboard_report.html']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/data/data_drift_dashboard_report.html
[2024-11-26T12:09:46.206+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/data/data_drift_dashboard_report.html
[2024-11-26T12:09:46.217+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=drift_detection_dag, task_id=send_email, execution_date=20241126T120921, start_date=20241126T120946, end_date=20241126T120946
[2024-11-26T12:09:46.230+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 77 for task send_email (/opt/airflow/data/data_drift_dashboard_report.html; 1285)
[2024-11-26T12:09:46.245+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-26T12:09:46.268+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
